### PR TITLE
Create a Dependabot configuration

### PR DESCRIPTION
**Pull request by Varriount**
Create a Dependabot configuration for NPM/Yarn and GitHub Actions

### CODE REVIEW

**Comment by ghost91-** [comment]
What’s the point of configuring it for npm/yarn? This is not an npm package.

**Comment by Varriount** [comment]
@ghost91- If a user of the template uses NPM/Yarn, this will tell Dependabot to file PRs for dependency updates.

**Comment by ghost91-** [comment]
> @ghost91- If a user of the template uses NPM/Yarn, this will tell Dependabot to file PRs for dependency updates.

The thing is: Most users of the template don’t.

As the template itself doesn’t use npm/yarn, I think that’s out of scope. Otherwise, you could also make a case for any other package manager to be included.

The template is intentionally kept simple, so I wouldn't add anything that doesn’t have a direct benefit. I think it’s even debatable if dependabot should be added at all.

**Comment by Varriount** [comment]
Ok, I've removed the NPM/Yarn configuration. Regarding the GitHub Action configuration, the reason I added it is because if there's a security bug or fix in a GitHub Action, it's usually best for the user to update as soon as possible.

**Review by ghost91- — APPROVED** [review]

**Review by cswendrowski — APPROVED** [review]

**Pull request merged**
